### ISSUE TITLE
Add team

### ISSUE THREAD

**Issue by Monal5031** [anshumanv/Student-Lifecycle-Management-Desktop#3]
Add the whole team @anshumanv
Mention M2A2

**Comment by anshumanv** [comment]
Yes

**Comment by anshumanv** [comment]
I just copied down the template :laughing:

**Comment by Monal5031** [comment]
Please do the changes :stuck_out_tongue: 
#EatWithYourTeam

**Comment by anshumanv** [comment]
Fixed in 9da476a
